# Exploratory Data Analysis (EDA)

### **All exercises will be using your chosen dataset**

## Step 1: Import your dataset using the tutorial from the slides

## Step 2: Install necessary libraries. We are using Pandas and NumPy for week 1

In [1]:
import pandas as pd
import numpy as np

## Exercises

### Pandas and NumPy Docs for Reference

#### [Pandas Documentation](https://pandas.pydata.org/docs/)

#### [NumPy Documentation](https://numpy.org/devdocs/)

## Pandas

### Exercise 1: Previewing The Dataset

In [2]:
# TODO: Read dataset into a Pandas dataframe
df = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [3]:
# TODO: print the first 7 rows
print(df.head(7))

      id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes
1  51676  Female  61.0             0              0          Yes
2  31112    Male  80.0             0              1          Yes
3  60182  Female  49.0             0              0          Yes
4   1665  Female  79.0             1              0          Yes
5  56669    Male  81.0             0              0          Yes
6  53882    Male  74.0             1              1          Yes

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked
1  Self-employed          Rural             202.21   NaN     never smoked
2        Private          Rural             105.92  32.5     never smoked
3        Private          Urban             171.23  34.4           smokes
4  Self-employed          Rural             174.12  24.0     never smoked
5        Private          Urban             186.21  29.0  formerly smoked
6        Private          Rural              70.09  27.4     never smoked

   stroke
0       1
1       1
2       1
3       1
4       1
5       1
6       1

In [4]:
# TODO: print the last 5 rows
print(df.tail(5))

         id  gender   age  hypertension  heart_disease ever_married  \
5105  18234  Female  80.0             1              0          Yes
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
5105        Private          Urban              83.75   NaN     never smoked
5106  Self-employed          Urban             125.20  40.0     never smoked
5107  Self-employed          Rural              82.99  30.6     never smoked
5108        Private          Rural             166.29  25.6  formerly smoked
5109       Govt_job          Urban              85.28  26.2          Unknown

      stroke
5105       0
5106       0
5107       0
5108       0
5109       0

In [5]:
# TODO: print 5 random rows
print(df.sample(5))

         id  gender   age  hypertension  heart_disease ever_married  \
4157  47410  Female  14.0             0              0           No
539   40622  Female  43.0             0              0          Yes
1646  31461  Female  48.0             0              1          Yes
2823  22254  Female  76.0             0              0          Yes
4451   6472  Female  78.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
4157       children          Rural             111.76  24.8          Unknown
539         Private          Rural              80.83  51.5          Unknown
1646  Self-employed          Urban             101.22   NaN  formerly smoked
2823        Private          Rural             113.68  22.8          Unknown
4451       Govt_job          Urban             101.76   NaN           smokes

      stroke
4157       0
539        0
1646       0
2823       0
4451       0

Write what each row and what each column represents:

### Exercise 2: Examining features/shape

In [6]:
# TODO: Print dataset shape
print(df.shape)

(5110, 12)

In [7]:
# TODO: Print the names of the columns
print(df.columns)

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='str')

In [8]:
# TODO: Drop any identifier columns like names, id, etc...
df = df.drop(columns=['id'])

In [9]:
# TODO: Print all the data types of the columns
print(df.dtypes)

gender                   str
age                  float64
hypertension           int64
heart_disease          int64
ever_married             str
work_type                str
Residence_type           str
avg_glucose_level    float64
bmi                  float64
smoking_status           str
stroke                 int64
dtype: object

In [10]:
# TODO: Find the counts of each data type
print(df.dtypes.value_counts())

str        5
float64    3
int64      3
Name: count, dtype: int64

### Exercise 3: Missing/Duplicate Values

In [11]:
# TODO: Find the number of missing values per column
print(df.isna().sum())

gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [12]:
# TODO: identify the column with the most missing values
df.isna().sum().idxmax()

'bmi'

In [13]:
# TODO: Either drop the rows with missing values or impute them
df = df.dropna()
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [14]:
# TODO: Drop duplicate rows if there are any
df.drop_duplicates(inplace=True)
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

### Exercise 4: Statistics

In [15]:
# TODO: Choose one numeric column and store its name in a variable
col = 'bmi'

In [16]:
# TODO: print a summary of statistics using .describe() for that column
print(df[col].describe())

count    4909.000000
mean       28.893237
std         7.854067
min        10.300000
25%        23.500000
50%        28.100000
75%        33.100000
max        97.600000
Name: bmi, dtype: float64

In [17]:
# TODO: Compare the mean and median of the column
print(f"Mean: {df[col].mean()}")
print(f"Median: {df[col].median()}")

Mean: 28.893236911794663
Median: 28.1

What can the mean and median of this column tell you about the distribution of data?

### Exercise 5: Filtering/GroupBy

In [18]:
# TODO: From any of the columns, look for suspicious values
# (like negative numbers)
df[df[col] < 0]

Empty DataFrame
Columns: [gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke]
Index: []

In [19]:
# TODO: From any categorical column, create and display a dataset that only
# contains one of the categories
df[df['work_type'] == 'Self-employed']

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
15,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1
21,Female,52.0,1,0,Yes,Self-employed,Urban,233.29,48.9,never smoked,1
22,Female,79.0,0,0,Yes,Self-employed,Urban,228.70,26.6,never smoked,1
25,Male,80.0,0,0,Yes,Self-employed,Rural,104.12,23.5,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5088,Female,64.0,1,0,Yes,Self-employed,Urban,76.89,30.2,Unknown,0
5097,Male,68.0,0,0,Yes,Self-employed,Urban,91.68,40.8,Unknown,0
5100,Male,82.0,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0

In [20]:
# TODO: Using that same categorical column, group by that column and find how
# many rows belong to each of the groups
df.groupby('work_type').size()

work_type
Govt_job          630
Never_worked       22
Private          2811
Self-employed     775
children          671
dtype: int64

Determine which group shows up the least and which shows up the most:

## NumPy

### Exercise 6 NumPy Operations

In [21]:
# TODO: Choose two numeric columns and put them into a list variable
cols = ['age', 'avg_glucose_level']

In [22]:
# TODO: Convert those columns into a numpy matrix (ndarray)
ndarray = df[cols].to_numpy()

In [23]:
# TODO: Print the shape of the data
print(ndarray.shape)

(4909, 2)

### Exercise 7: More Statistics

In [24]:
# TODO: Compute the mean of each columns (axis = 0)
ndarray.mean(axis=0)

array([ 42.8653738 , 105.30514972])

In [25]:
# TODO: Compute the standard deviation of the columns
ndarray.std(axis=0)

array([22.55281751, 44.41981565])

In [26]:
# TODO: Compute the mean of each row (axis = 1)
ndarray.mean(axis=1)

array([147.845,  92.96 , 110.115, ...,  58.995, 108.645,  64.64 ],
      shape=(4909,))

In [27]:
# TODO: Compute the std deviation of each row
ndarray.std(axis=1)

array([80.845, 12.96 , 61.115, ..., 23.995, 57.645, 20.64 ], shape=(4909,))

### Exercise 8: Math Operations

In [28]:
# TODO: Calculate the dot product of the two original columns (you can think of these columns as vectors)
dotProd = np.dot(ndarray[:, 0], ndarray[:, 1])

In [29]:
# TODO: Calculate the magnitude of both columns
col1 = ndarray[:, 0]
col2 = ndarray[:, 1]

mag1 = np.linalg.norm(col1)
mag2 = np.linalg.norm(col2)

print(mag1)
print(mag2)

3393.649493981369
8007.671577680992

In [30]:
# TODO: Find the cosine similarity (dot product / product of magnitudes)
cosSimilar = dotProd / (mag1 * mag2)

print(cosSimilar)

0.8580886973628298

The cosine similarity is used to determine how related two features are to each other. A high value indicates that these features are highly correlated which means that changes in one variable corresponds to changes in the other. This is called **collinearity**.

Using two or more highly correlated features in a machine learning algorithm can lead to numerous problems such as redundant information and reduced model reliability

### Exercise 9: Further Analysis

#### Continue exploring and gaining more insights into your data. Utilize the docs linked above.